version: '3'

services:
  nginx:
    image: nginx:1.23.1
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf