version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: pritunldb
    hostname: pritunldb
    network_mode: bridge
    volumes:
      - ./db:/data/db

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    depends_on:
        - mongo
    network_mode: bridge
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9700:9700
      - 8080:80
      - 4433:443
      - 1194:1194
      - 1194:1194/udp
      - 1195:1195/udp
      - 19270:19270
      - 19270:19270/udp
    environment:
      - TZ=UTC
      - REVERSE_PROXY=true